### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by dblock** [dblock/msiext#22]
Anyone actively using this project wants to do a 1.5 release?

@ramiabughazaleh @vladaver @romanws ?

**Comment by icnocop** [comment]
Yes, I can try.

I'll plan to create a build project on appveyor.

**Comment by dblock** [comment]
@icnocop You have collaborator access now. Lets get the downloads off my personal website too if possible. Thanks!

**Comment by icnocop** [comment]
[1.5 has just been released.](https://github.com/dblock/msiext/releases/tag/1.5) :)
