### ISSUE TITLE
ServiceCredDlg don't insert username

### ISSUE THREAD

**Issue by KlaasWedemeyer** [dblock/msiext#27]
Hello,
I use from the WixCommonUiExtenstion v1.5 the ServiceCredDlg.
It works fine. 
But after ein insert some characters in the username field, I open the userselect dialog, select a user and press ok, the name is not apply to the username field.
This is also happend, when I remove the letters from the username field. I have to leave the Dialog.
Thangs for help...

**Comment by dblock** [comment]
It could be a bug, too.

**Comment by KlaasWedemeyer** [comment]
What can I do to put this bug to the open bug list?

**Comment by dblock** [comment]
Don't expect anyone here to jump on reproducing and fixing it. That said, you can get help from people who are using or have used msiext and help with code. I would try to check the code out, build it, reproduce the problem with the sample/demo code here first.

**Comment by dblock** [comment]
Closed via a twin dialog hack in https://github.com/dblock/msiext/pull/33
