### ISSUE TITLE
Unable to run The sql script file 

### ISSUE THREAD

**Issue by waqar2012** [dblock/msiext#29]
Please find my sample project source code and sql script

[Sample Code.txt](https://github.com/dblock/msiext/files/381160/Sample.Code.txt)
[CreateBinaryTable_Encoded.txt]
(https://github.com/dblock/msiext/files/381162/CreateBinaryTable_Encoded.txt)

I am trying to run your sample but still not able to execute the sql file script. 

Please give response with some suggestion then may i will able to run my sql script file. 

I have already checked your sample that you have provided in the repository but still no success.

During installation it does not give any error . it installed successfully but not able to find my script run and create the database table.
I am using the wixdatasourceextension.
Kind regards,
waiting for your response.

**Comment by dblock** [comment]
You'll have to at least provide the relevant log lines for "not able to find my script run and create the database table".

**Comment by dblock** [comment]
Please use the [google group](https://groups.google.com/group/msiext) for questions.

**Comment by waqar2012** [comment]
I have posted the question on https://groups.google.com/forum/#!topic/msiext/TZ0s5wSrvbw. Kindly help me if any idea
