### ISSUE TITLE
g++ setup and config

### ISSUE THREAD

**Issue by privateCoins** [dblock/msiext#37]
What default settings compile options etc... does one have to use on these to get things to work and just compile?

Trying to learn and it never fails this crap always happens.  Everything does not compile it gives tons of errors and everything is a mess wrong string lcpstr cant the string setup in code. or like this time I include the alt source files and get hundreds of errors stating  const' cannot be overloaded with
* has not been declared
expected ')' before 'int'
Just using these right out of the box but no nothing ever works any more
cant even get anything to compile.
Is there some magic setting or switch that one needs to use in order for this stuff to compile or do I have to use an old compiler as everything has changed and new compilers reject all older code?
Also why are all the solutions written so that a lpcstr can accept a wchar_t when this always fails.
Even though I look up lpcstr and it is supposed to accept the str type but there are literally hundreds of these solutions written that no longer work because either this is not the case or there is some basic settings or compile options no one is sharing.
Seriously how is someone supposed to learn if you don't provide basic instructions somewhere or why have you changed it so nothing works with no solutions available anywhere.

**Comment by dblock** [comment]
https://github.com/dblock/msiext/blob/master/CONTRIBUTING.md#development-environment
